name: Publish releases to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Publish package
        run: gradle -Prelease publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
           ORG_GRADLE_PROJECT_sonatypeUsername : ${{ secrets.OSSRH_USERNAME }}
           ORG_GRADLE_PROJECT_sonatypePassword : ${{ secrets.OSSRH_PASSWORD }}
           ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
           ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_SECRET }}